version: "3.9"

services:
    #app
    projeto-ks-back:
        container_name: projeto-ks-back
        build:
            args:
                user: gedeom
                uid: 1000
            context: .
            dockerfile: Dockerfile
        image: laravel
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - laravel

    # nginx
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        restart: always
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql
        networks:
            - laravel

    # mariadb
    mysql:
        container_name: mysql
        image: mariadb:10.6
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: f7*@S3G
        volumes:
            - ./docker/init:/docker-entrypoint-initdb.d
        ports:
            - "3306:3306"
        networks:
            - laravel

    # php
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php
        volumes:
            - ./:/var/www
            - ./:/var/www/projeto-ks-back
        ports:
            - "9000:9000"
        networks:
            - laravel
        working_dir: /var/www

    # queue
    queue:
        container_name: queue
        image: projeto-ks-back
        build:
            args:
                user: gedeom
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        restart: unless-stopped
        volumes:
            - ./:/var/www/projeto-ks-back
        depends_on:
            - redis
            - projeto-ks-back
        networks:
            - laravel

    #redis
    redis:
        container_name: redis
        image: redis:latest
        networks:
            - laravel

        #composer
    composer:
        container_name: composer
        build: .
        depends_on:
            - php
            - redis
            - queue
        volumes:
            - ./:/var/www
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
